---
title: "SJV_TDS"
author: "Rich Pauloo"
date: "July 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## # Tulare Basin Groundwater Quality Map (TDS)

## Set wd(), load requried packages, and load data
```{r set wd, load required packages, and load data}
setwd("E:/rpauloo/Documents/GitHub/Contaminant-Mapping")

required.packages <- c("sp", "XML", "rgdal", "rgeos", "raster", 
                       "dismo", "leaflet", "RColorBrewer", "classInt")
lapply(required.packages, library, character.only = TRUE)

dat = read.csv(file = "SJV_decadal_gw_qual.csv", stringsAsFactors = FALSE)
```


## Explore by plotting data
```{r explore by plotting data}
plot(dat$DEC_LONG_VA, dat$DEC_LAT_VA)
```


## Data Analysis and creation of spatial points df
```{r create spatial points df}
well_coords = cbind(dat$DEC_LONG_VA, dat$DEC_LAT_VA)
pts = SpatialPoints(well_coords) # still needs a CRS (coordinate reference system)
df = dat[,1:6]
df$dec_change = df[, 6] - df[, 4]
# create spatial points data frame
ptsdf = SpatialPointsDataFrame(pts, data = df)
```


## Define color palette
```{r define color palette}
co = c("blue", "steelblue2", "seashell1", "orangered2", "red")
pal = colorNumeric(palette = co, 
                   domain = df$dec_change)
```


## Create map
```{r create map}
map = leaflet(data = ptsdf) 
map = addTiles(map)
map %>%
  addCircleMarkers(map,
    lng = well_coords[,1], # longitude
    lat = well_coords[,2], # latitude
    radius = 8, # fixed radius size
    color = ~pal(dec_change),
    stroke = FALSE, 
    fillOpacity = 0.9,
    popup = paste(as.character(ptsdf$dec_change), 
                  "mg/L TDS", 
                  by = " ")
  ) %>%
  
  addLegend("topright", pal = pal,
            values = ~dec_change,
            title = "10yr change in GW TDS",
            labFormat = labelFormat(suffix = " mg/L"),
            opacity = 1
  ) %>%
  
  addProviderTiles(providers$Esri.WorldTerrain) # override default map
```